### ISSUE TITLE
USER STORY: USER COMMENT DELETION

### ISSUE THREAD

**Issue by dickiegog** [dickiegog/Project_4#12]
### User Story
As a user, I can delete comments I’ve posted so that I can remove any unwanted or irrelevant content.

### Acceptance Criteria
- The user can delete comments they've posted from the blog post page.
- Deleted comments are removed from the post and the database.
- The user is notified once their comment has been successfully deleted.

### Tasks (Yet to Implement)
- [x] Add a "Delete Comment" option for users on their comments.
- [x] Ensure the comment is removed from the database.
- [x] Test the comment deletion functionality.
