### ISSUE TITLE
USER STORY POST SEARCH FUNCTIONALITY

### ISSUE THREAD

**Issue by dickiegog** [dickiegog/Project_4#9]
### User Story
As a user, I can search for blog posts by keyword so that I can easily find relevant content.

### Acceptance Criteria
- The user can search for posts using a keyword input.
- Search results display all posts that match the keyword in the title or body.
- A message is shown if no search results are found.
- The search bar is visible on all blog pages.

### Nice to Have
- Search by categories as well

### Tasks
- [x] Add a search bar to the blog homepage.
- [x] Implement search functionality for titles and content.
- [x] Display matching search results or a "no results" message.
- [x] Add a dropdown of popular categories that can be assigned and used to filter shifts
